### ISSUE TITLE
How To Translate Genshin Impact

### ISSUE THREAD

**Issue by hrastgh1** [bbepis/XUnity.AutoTranslator#299]
Hello

I'm trying Genshin Impact in my native language, Armenian, but when I launch XUnity.AutoTranslator ReiPatcher it brings me a window like this and closes after a few seconds.

![image](https://user-images.githubusercontent.com/21078676/180664128-cdae0f77-daee-43d3-bc31-edd471c47a1c.png)

Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'C:\Program Files\Genshin Impact\Genshin Impact game\ReiPatcher' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at XUnity.AutoTranslator.Setup.Program.AddFile(String fileName, Byte[] bytes, Boolean overwrite)
   at XUnity.AutoTranslator.Setup.Program.Main(String[] args)

**Comment by zclimber** [comment]
This is because of Genshin Impact is located in Program Files directory, and to modify files in it you need to run setup as administrator.

And I don't think translating Genshin Impact will work, anyway - you have to launch this game through launcher, and it will run original executable, not ReiPatcher one.
