### ISSUE TITLE
Shadows of Doubt [it does not work]

### ISSUE THREAD

**Issue by ziomik** [bbepis/XUnity.AutoTranslator#378]
The "AutoTranslator" folder is not created and the application closes

also tried as a mod on "MelonLoader". MelonLoader doesn't crash but gives an error:

`[10:29:04.749] [XUnity_Auto_Translator] System.TypeLoadException: Could not load type 'UnityEngine.Application' from assembly 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at XUnity.Common.Utilities.Paths.GetAndSetGameRoot()
   at XUnity.Common.Utilities.Paths.get_GameRoot()
   at XUnity.AutoTranslator.Plugin.Core.DefaultPluginEnvironment..ctor(Boolean allowDefaultInitializeHarmonyDetourBridge)
   at XUnity.AutoTranslator.Plugin.Core.PluginLoader.Load(Boolean allowDefaultInitializeHarmonyDetourBridge)
   at XUnity.AutoTranslator.Plugin.MelonMod.AutoTranslatorPlugin.OnApplicationLateStart()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143`

**Comment by ziomik** [comment]
[Message: Preloader] BepInEx 6.0.0-be.577 - Shadows of Doubt
[Message: Preloader] BLEEDING EDGE Build #577 from ec79ad057b20c302c17b34e63906ee398352d852 at master
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   : Preloader] Running under Unity v2021.1.0
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [XUnity Auto Translator 5.0.0]
[Info   :Unhollower] Registered mono type XUnity.AutoTranslator.Plugin.Core.PluginLoader+AutoTranslatorProxyBehaviour in il2cpp domain
[Info   :   BepInEx] Loading [XUnity Resource Redirector 2.0.0]
[Message:   BepInEx] Chainloader startup complete
[Info   :XUnity.AutoTranslator] Force loading ALL proxy assemblies.
[Warning:XUnity.AutoTranslator] Could not find 'UnityEngine.GUI+ToolbarButtonSize' in IL2CPP domain even though it could be found in the managed domain.
[Warning:XUnity.AutoTranslator] Could not find 'UnityEngine.AssetBundle' in IL2CPP domain even though it could be found in the managed domain.
[Info   :XUnity.AutoTranslator] Version of TextMesh Pro: 1.4.0.
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type TMPro.TMP_Text and name SetCharArray and parameters (UnhollowerBaseLib.Il2CppStructArray<int>, int, int)
[Warning:XUnity.AutoTranslator] Could not hook 'TMP_Text_SetCharArray_Hook3'. Likely due differences between different versions of the engine or text framework.
[Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [2021.1.15f1] game.
[Info   :Unhollower] Registered mono type XUnity.AutoTranslator.Plugin.Core.Il2CppManagedEnumerator in il2cpp domain
[Error  :XUnity.AutoTranslator] An error occurred while setting up UI.
System.TypeInitializationException: The type initializer for 'XUnity.AutoTranslator.Plugin.Core.UI.GUIUtil' threw an exception. ---> System.MissingMethodException: Method not found: void UnityEngine.RectOffset..ctor(int,int,int,int)
   --- End of inner exception stack trace ---
  at XUnity.AutoTranslator.Plugin.Core.UI.ToggleViewModel..ctor (System.String text, System.String enabledTooltip, System.String disabledTooltip, System.Action onToggled, System.Func`1[TResult] isToggled, System.Boolean enabled) [0x00006] in <0ea2703889c145a096d82030e94f7e76>:0
  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.CreateXuaViewModel () [0x00005] in <0ea2703889c145a096d82030e94f7e76>:0
  at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.InitializeGUI () [0x00015] in <0ea2703889c145a096d82030e94f7e76>:0
[Info   :XUnity.AutoTranslator] Skipping plugin scan because no plugin-specific translations has been registered.
[Warning:XUnity.AutoTranslator] An error occurred while setting up GoogleTranslate FSID. Using random instead.

[Error  :XUnity.AutoTranslator] Error occurred while retrieving translation. Nothing was returned.
[Error  :XUnity.AutoTranslator] Failed: 'Press Any Button'
[Error  :XUnity.AutoTranslator] Error occurred while retrieving translation. Nothing was returned.
[Error  :XUnity.AutoTranslator] Failed: 'Monday
Jan 2nd '
[Error  :XUnity.AutoTranslator] Failed: '[Pause]'
[Error  :XUnity.AutoTranslator] Failed: '[TimeText]
'
[Error  :XUnity.AutoTranslator] Failed: '[Location Text]'
[Error  :XUnity.AutoTranslator] Failed: '[Cr999]'
[Error  :XUnity.AutoTranslator] Failed: '[Resolve]'
[Error  :XUnity.AutoTranslator] Failed: 'F1'
[Error  :XUnity.AutoTranslator] Failed: '[Interactable Item]'
[Error  :XUnity.AutoTranslator] Failed: 'Shadows of Doubt'
[Error  :XUnity.AutoTranslator] Failed: 'v33.14'
[Error  :XUnity.AutoTranslator] A batch operation failed. Disabling batching and restarting failed jobs.
[Info   :XUnity.AutoTranslator] Re-enabled batching.
[Error  :XUnity.AutoTranslator] Error occurred while retrieving translation. Nothing was returned.
[Error  :XUnity.AutoTranslator] Failed: 'v33.14'
[Error  :XUnity.AutoTranslator] Error occurred while retrieving translation. Nothing was returned.
[Error  :XUnity.AutoTranslator] Failed: 'Shadows of Doubt'
[Error  :XUnity.AutoTranslator] Failed: '[Interactable Item]'
[Error  :XUnity.AutoTranslator] Failed: 'F1'
[Error  :XUnity.AutoTranslator] Failed: '[Resolve]'
[Error  :XUnity.AutoTranslator] Failed: '[Cr999]'
[Error  :XUnity.AutoTranslator] Failed: '[Location Text]'
[Error  :XUnity.AutoTranslator] Failed: '[TimeText]
'
[Error  :XUnity.AutoTranslator] Failed: '[Pause]'
[Error  :XUnity.AutoTranslator] Failed: 'Monday
Jan 2nd '
[Error  :XUnity.AutoTranslator] Failed: 'Save Game'
[Error  :XUnity.AutoTranslator] A batch operation failed. Disabling batching and restarting failed jobs.
[Info   :XUnity.AutoTranslator] Re-enabled batching.
[Error  :XUnity.AutoTranslator] Error occurred while retrieving translation. Nothing was returned.
[Error  :XUnity.AutoTranslator] Failed: 'Save Game'
[Error  :XUnity.AutoTranslator] 5 or more consecutive errors occurred. Shutting down translator endpoint.
[Warning:XUnity.AutoTranslator] Dequeued: 'Monday
Jan 2nd '
[Warning:XUnity.AutoTranslator] Dequeued: '[Pause]'
[Warning:XUnity.AutoTranslator] Dequeued: '[TimeText]
'
[Warning:XUnity.AutoTranslator] Dequeued: '[Location Text]'
[Warning:XUnity.AutoTranslator] Dequeued: '[Cr999]'
[Warning:XUnity.AutoTranslator] Dequeued: '[Resolve]'
[Warning:XUnity.AutoTranslator] Dequeued: 'F1'
[Warning:XUnity.AutoTranslator] Dequeued: '[Interactable Item]'
[Warning:XUnity.AutoTranslator] Dequeued: 'Shadows of Doubt'
[Warning:XUnity.AutoTranslator] Dequeued: 'Credits'
[Warning:XUnity.AutoTranslator] Dequeued: 'Settings'
[Warning:XUnity.AutoTranslator] Dequeued: 'Load Game'
[Warning:XUnity.AutoTranslator] Dequeued: 'Exit'
[Warning:XUnity.AutoTranslator] Dequeued: 'New Game'
[Warning:XUnity.AutoTranslator] Dequeued: 'Help'
[Warning:XUnity.AutoTranslator] Dequeued: 'Report Bug'
[Warning:XUnity.AutoTranslator] Dequeued: 'Resume Game'

**Comment by ziomik** [comment]
Was the project abandoned?
