### ISSUE TITLE
Is the latest version of AutoTranslator IL2CPP not compatible with the latest BepInEx?

### ISSUE THREAD

**Issue by SisconM** [bbepis/XUnity.AutoTranslator#394]
As some other people reported, their AutoTranslation folder does not appear, I looked into the log and stuff, and BepInEx doesn't even load the plugin (0 plugins loaded). 
Is this related to the fact that "Builds after 6.0.0-be.577 use updated tooling and .NET 6 for Il2Cpp." 
Sadly for some newer games, only the latest BepInEx can run on it.

**Comment by AfflictedGameDev** [comment]
Got this issue too on newly release game
BepInEx version 6.0.0-be.670 (Other version doesn't work with this newly release game, game would crash, not load)

The log,
Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2021.3.21f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 0 plugins to load

All of the AutoTanslator IL2CPP files are correctly sitting in the BepInEx\plugins

**Comment by Kevga** [comment]
You can give my fork a shot, we use this on a Unity 2021.3 game with one of the newer BepInEx 6 builds.
https://github.com/Kevga/XUnity.AutoTranslator

**Comment by zigma9114** [comment]
> You can give my fork a shot, we use this on a Unity 2021.3 game with one of the newer BepInEx 6 builds. https://github.com/Kevga/XUnity.AutoTranslator

can you make a downloadable release? i dont know how to compile myself

**Comment by bai198611** [comment]
> You can give my fork a shot, we use this on a Unity 2021.3 game with one of the newer BepInEx 6 builds. https://github.com/Kevga/XUnity.AutoTranslator

Can you pack a finished product?

**Comment by KAPTOHKA** [comment]
Thanks for the fix, but the folder doesn't appear...
What am I doing wrong?
Or where to dig?

`[Info   :Il2CppInteropGen] Done!
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [XUnity Auto Translator 5.2.0]
[Error  :   BepInEx] Error loading [XUnity Auto Translator 5.2.0]: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'System.String BepInEx.Unity.IL2CPP.Preloader.get_IL2CPPInteropAssemblyPath()'.
   at XUnity.AutoTranslator.Plugin.BepInEx.AutoTranslatorPlugin..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(PluginInfo pluginInfo, Assembly pluginAssembly) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 129
   at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 411
[Info   :   BepInEx] Loading [XUnity Resource Redirector 2.0.0]
[Message:   BepInEx] Chainloader startup complete
`

**Comment by Kevga** [comment]
Oh, I wasn't aware of this. I built XUAT against a BepInEx build from this pull request, which publicizes a property that was needed by AutoTranslator: https://github.com/BepInEx/BepInEx/pull/611
You'd need to either
1) build and use that version of BepInEx
2) wait for it to be merged into master and included in an official build
3) modify XUAT to get access to that property in a different way (BepInEx publicizer or reflection)

**Comment by bai198611** [comment]
> Oh, I wasn't aware of this. I built XUAT against a BepInEx build from this pull request, which publicizes a property that was needed by AutoTranslator: [BepInEx/BepInEx#611](https://github.com/BepInEx/BepInEx/pull/611) You'd need to either
> 
> 1. build and use that version of BepInEx
> 2. wait for it to be merged into master and included in an official build
> 3. modify XUAT to get access to that property in a different way (BepInEx publicizer or reflection)

https://github.com/bbepis/XUnity.AutoTranslator/issues/394#issuecomment-1647704857

**Comment by bai198611** [comment]
Please integrate a modified version, many games are now unrecognizable with 5.20

> Oh, I wasn't aware of this. I built XUAT against a BepInEx build from this pull request, which publicizes a property that was needed by AutoTranslator: [BepInEx/BepInEx#611](https://github.com/BepInEx/BepInEx/pull/611) You'd need to either
> 
> 1. build and use that version of BepInEx
> 2. wait for it to be merged into master and included in an official build
> 3. modify XUAT to get access to that property in a different way (BepInEx publicizer or reflection)
 


Please integrate a modified version, many games are now unrecognizable with 5.20

**Comment by bai198611** [comment]
> 哦，我不知道这一点。我根据此拉取请求针对 BepInEx 构建构建了 XUAT，该请求公开了 AutoTranslator 所需的属性：BepInEx/BepInEx#611 你需要要么
> 
> 1. 构建并使用该版本的 BepInEx
> 2. 等待它合并到 master 并包含在正式版本中
> 3. 修改 XUAT 以以不同的方式访问该属性（BepInEx 宣传器或反射）

Please integrate a modified version, many games are now unrecognizable with 5.20

**Comment by KAPTOHKA** [comment]
The combination of [BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.672](https://builds.bepinex.dev/projects/bepinex_be) and [XUnity.AutoTranslator(v5.3.0)](https://github.com/bbepis/XUnity.AutoTranslator/releases) also work correctly...)))
