### ISSUE TITLE
Could not load type 'UnityEngine.Input' from assembly 'UnityEngine.CoreModule

### ISSUE THREAD

**Issue by prstzbd** [bbepis/XUnity.AutoTranslator#422]
In the game with BeplnEX IL2cpp, the menu doesn't open and all keyboard shortcuts don't work

> [Warning:XUnity.AutoTranslator] Input API is not available!
System.TypeLoadException: Could not load type 'UnityEngine.Input' from assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInput()
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInputSafe()

**Comment by Yuxin-Cao1827** [comment]
same here happened to me. The game I'm trying to patch also generated an exception:

> An error occurred while settings up scene-load scans.
System.NotSupportedException: Method unstripping failed
   at lambda_method2(Closure , UnityAction`2 )
   at XUnity.AutoTranslator.Plugin.Utilities.TranslationScopeHelper.RegisterSceneLoadCallback(Action`1 sceneLoaded)
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.EnableSceneLoadScan()

**Comment by ManlyMarco** [comment]
Fixed in #531
