### ISSUE TITLE
Cannot translate Reverse 1999

### ISSUE THREAD

**Issue by Khali1999** [bbepis/XUnity.AutoTranslator#432]
I've tried almost every method but maybe I'm doing something wrong 

![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/149176222/11e4d0fa-689d-4f95-abb4-90d797712cbe)

I know what the GameAssembly.dll being there means, but still no way to make it work, any help?

**Comment by Atamg1994** [comment]
Apparently you uploaded a version for MelonLoader
but MelonLoader itself is not visible, did you install it at all?

**Comment by Atamg1994** [comment]
https://melonwiki.xyz/#/

**Comment by Khali1999** [comment]
I tried MelonLoader, maybe I didn't uninstall it correctly, the problem is that nothing works with this game

**Comment by YogSottot** [comment]
Tried this game with bepinex.  
It's not working.  Invalid or corrupt metadata (magic number check failed)

XUnity.AutoTranslator-BepInEx-IL2CPP-5.3.0
BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.672+472e950

```
[Message: Preloader] BepInEx 6.0.0-be.672 - reverse1999
[Message: Preloader] Built from commit 472e950179f4a5ab2e4a89f26dba793795fb6811
[Info   :   BepInEx] System platform: Windows 10 (Wine 8.0) 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2019.4.40f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Message:InteropManager] Downloading unity base libraries
[Message:InteropManager] Extracting downloaded unity base libraries
[Message:InteropManager] Running Cpp2IL to generate dummy assemblies
[Info   :    Cpp2IL] [Library] Initializing Metadata...
[Error  :InteropManager] Failed to generate Il2Cpp interop assemblies: Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initia
lizing LibCpp2IL!
 ---> System.FormatException: Invalid or corrupt metadata (magic number check failed)
   at LibCpp2IL.Metadata.Il2CppMetadata.ReadFrom(Byte[] bytes, UnityVersion unityVersion) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/Metadata/Il2CppMetadata.cs:line 65
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, UnityVersion unityVersion) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/LibCpp2IlMain.cs:line 150
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, UnityVersion unityVersion) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/LibCpp2IlMain.cs:line 203
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in /_/Cpp2IL.Core/Cpp2IlApi.cs:line 61
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in /_/Cpp2IL.Core/Cpp2IlApi.cs:line 67
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.RunCpp2Il() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs:line 282
   at BepInEx.Unity.IL2CPP.Il2CppInteropManager.GenerateInteropAssemblies() in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/Il2CppInteropManager.cs:line 213
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
00e0:err:eventlog:ReportEventW L"Application: reverse1999.exe\nCoreCLR Version: 6.0.722.32202\n.NET Version: 6.0.7\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.IO.FileNotFoundException: Could not load file or assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neu"...
```

**Comment by Khali1999** [comment]
Yeah same here, sadly it's not possible to translate at the moment.

Same happens with the game "Punishing Gray Raven", it's really a shame :/

**Comment by YogSottot** [comment]
> Same happens with the game "Punishing Gray Raven", it's really a shame :/

Everything works in this game

For windows:
- Create a ``il2cpp_data`` directory in ``$(Game_root_dir)/PGR_Data`` and create a symlink from ``$(Game_root_dir)/PGR_Data/Native/Data/Metadata/`` to ```$(Game_root_dir)/PGR_Data/il2cpp_data/Metadata/```.

For linux also:
- Add winhttp in winecfg dll override
- winetricks: corefonts, vcrun2022, winemono

**Comment by Khali1999** [comment]
> > Same happens with the game "Punishing Gray Raven", it's really a shame :/
> 
> Everything works in Punishing Gray Raven
> 
> For windows:
> 
> * Create a `il2cpp_data` directory in `$(Game_root_dir)/PGR_Data` and create a symlink from `$(Game_root_dir)/PGR_Data/Native/Data/Metadata/` to `$(Game_root_dir)/PGR_Data/il2cpp_data/Metadata/`.
> 
> For linux also:
> 
> * Add winhttp in winecfg dll override
> * winetricks: corefonts, vcrun2022, winemono
> 
> Tested with: BepInEx-Unity.IL2CPP-win-x64-6.0.0-be.672+472e950 XUnity.AutoTranslator-BepInEx-IL2CPP-5.3.0

I don't know what a symlink is or how do I create it, any help?

**Comment by YogSottot** [comment]
> I don't know what a symlink is or how do I create it,


https://github.com/arnobpl/SymlinkCreator
https://superuser.com/questions/1020821/how-can-i-create-a-symbolic-link-on-windows-10

**Comment by Khali1999** [comment]
> > I don't know what a symlink is or how do I create it,
> 
> https://github.com/arnobpl/SymlinkCreator https://superuser.com/questions/1020821/how-can-i-create-a-symbolic-link-on-windows-10

Thanks so much! It's working, but it won't translate some parts of the UI, just like this

![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/149176222/4c802594-f279-40fe-bfa8-1ba1d4793db8)

Any help?

Also, how can I fix this? The text overlaps the picture, I'm thinking about centering it and placing it like a column to try to fit the text in the box. Sorry for my bad english

![image](https://github.com/bbepis/XUnity.AutoTranslator/assets/149176222/4ef4708c-9c01-4544-84f8-bf7919df6697)

Thanks a lot for the help!!

**Comment by YogSottot** [comment]
> Also, how can I fix this? The text overlaps the picture, 

Try changing the font or font size.
Examine the settings in the configuration file.

I'm not interested in this game, so I can't help.

**Comment by AllenWalkerED** [comment]
> > > I don't know what a symlink is or how do I create it,
> > 
> > 
> > https://github.com/arnobpl/SymlinkCreator https://superuser.com/questions/1020821/how-can-i-create-a-symbolic-link-on-windows-10
> 
> Thanks so much! It's working, but it won't translate some parts of the UI, just like this
> 
> ![image](https://private-user-images.githubusercontent.com/149176222/280146573-4c802594-f279-40fe-bfa8-1ba1d4793db8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjUyNTIsIm5iZiI6MTcwNTgyNDk1MiwicGF0aCI6Ii8xNDkxNzYyMjIvMjgwMTQ2NTczLTRjODAyNTk0LWYyNzktNDBmZS1iZmE4LTFiYTFkNDc5M2RiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQwODE1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDRjNGQ3YzNlZmExZGQwZWUxMmJiMDkxZTU0YmE0MTNkYzk2MGM1ZjBkYjhiNzcwYzFlYjY4YTUzOGRmNDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v8MHfiA6EI1KUa-dpj2rnJPqbPCXoAezvvQtRvFI9Nw)
> 
> Any help?
> 
> Also, how can I fix this? The text overlaps the picture, I'm thinking about centering it and placing it like a column to try to fit the text in the box. Sorry for my bad english
> 
> ![image](https://private-user-images.githubusercontent.com/149176222/280147075-4ef4708c-9c01-4544-84f8-bf7919df6697.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjUyNTIsIm5iZiI6MTcwNTgyNDk1MiwicGF0aCI6Ii8xNDkxNzYyMjIvMjgwMTQ3MDc1LTRlZjQ3MDhjLTljMDEtNDU0NC04NGY4LWJmNzkxOWRmNjY5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQwODE1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGUzMjljNjQ2MmMxYTgwYzZmNDc1ZDljMThjNDM2ODFlZmQ4Y2E2YzNlNmMxNDg0NDBiNGRmNGU4ZDI1MDQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Na0xnwOCRmQXxiJBgr6vGwNUvC8EqQBsZPZcf1IGd8)
> 
> Thanks a lot for the help!!



> > > I don't know what a symlink is or how do I create it,
> > 
> > 
> > https://github.com/arnobpl/SymlinkCreator https://superuser.com/questions/1020821/how-can-i-create-a-symbolic-link-on-windows-10
> 
> Thanks so much! It's working, but it won't translate some parts of the UI, just like this
> 
> ![image](https://private-user-images.githubusercontent.com/149176222/280146573-4c802594-f279-40fe-bfa8-1ba1d4793db8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjUzMzIsIm5iZiI6MTcwNTgyNTAzMiwicGF0aCI6Ii8xNDkxNzYyMjIvMjgwMTQ2NTczLTRjODAyNTk0LWYyNzktNDBmZS1iZmE4LTFiYTFkNDc5M2RiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQwODE3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTBjYzBlZTNhMjllOTBiYWZhZDU2YTU4ODI2NTE1NTNkYzQyZjc5YjBjYTViNmFiNzk4MzQ5MmNkNjFhNDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BOjm0txcAk8bRsogsrs7TsikJr-f4FmUmnypPq9jSGU)
> 
> Any help?
> 
> Also, how can I fix this? The text overlaps the picture, I'm thinking about centering it and placing it like a column to try to fit the text in the box. Sorry for my bad english
> 
> ![image](https://private-user-images.githubusercontent.com/149176222/280147075-4ef4708c-9c01-4544-84f8-bf7919df6697.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjUzMzIsIm5iZiI6MTcwNTgyNTAzMiwicGF0aCI6Ii8xNDkxNzYyMjIvMjgwMTQ3MDc1LTRlZjQ3MDhjLTljMDEtNDU0NC04NGY4LWJmNzkxOWRmNjY5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQwODE3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjdjODJjZThkYjBiY2NkMDQ0OTIzMGVlNzY2NzlmM2VmYTgyMjIwZDUxOThmMWY1MjU5YWE0MjUxZTI4YzhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ye3nKKtTh_37NZ6sIr0jxaUV4nzxZLd7HtLTi2TW84g)
> 
> Thanks a lot for the help!!

didn't work for me on the latest version of the game. Does it still work for you until now?
