### ISSUE TITLE
sea of star

### ISSUE THREAD

**Issue by drakengard780** [bbepis/XUnity.AutoTranslator#445]
hi possible to translate thise game? thise is the log 

[NewEntryPoint] Passing ptr to LoadAssemblyAndGetFuncPtr back to host...
[NewEntryPoint] Configuring imports...
[NewEntryPoint] Initializing. In default load context: True
[09:52:48.474] ------------------------------
[09:52:48.474] MelonLoader v0.6.1 Open-Beta
[09:52:48.475] OS: Windows 10
[09:52:48.475] Hash Code: 696B58144EEC73C72FA36A811CA73312EEE4EC28AD5E3527BDA1E14F388A
[09:52:48.475] ------------------------------
[09:52:48.475] Game Type: Il2cpp
[09:52:48.475] Game Arch: x64
[09:52:48.476] ------------------------------
[09:52:48.476] Core::BasePath = E:\Sea of Stars
[09:52:48.476] Game::BasePath = E:\Sea of Stars
[09:52:48.476] Game::DataPath = E:\Sea of Stars\SeaOfStars_Data
[09:52:48.476] Game::ApplicationPath = E:\Sea of Stars\SeaOfStars.exe
[09:52:48.476] Runtime Type: net6
[09:52:48.554] ------------------------------
[09:52:48.554] Game Name: Sea of Stars
[09:52:48.554] Game Developer: Sabotage Studio
[09:52:48.555] Unity Version: 2021.3.25f1
[09:52:48.555] Game Version: UNKNOWN
[09:52:48.555] ------------------------------

[09:52:48.997] Preferences Loaded!

[09:52:49.011] Loading Plugins from 'E:\Sea of Stars\Plugins'...
[09:52:49.012] 0 Plugins loaded.
[NewEntryPoint] PreStarting.
[09:52:49.797] [MelonStartScreen] Initializing...
[09:52:49.823] [MelonStartScreen] Using Start Screen Theme: "Default"
[09:52:49.904] [MelonStartScreen] Failed to find the signature for field m_D3D12WaitForLastPresentationAndGetTimestamp in module. Signature: 48 89 5c 24 08 57 48 81 ec 90 00 00 00 0f 29 b4 24 80 00 00 00 48 8b d9
[09:52:49.916] Loading Il2CppAssemblyGenerator...
[09:52:49.921] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[09:52:50.071] [Il2CppAssemblyGenerator] Game Not Found on RemoteAPI Host (https://api.melonloader.com/api/v1/game/sea-of-stars)
[09:52:50.071] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[09:52:50.072] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[09:52:50.072] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[09:52:50.073] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[09:52:50.081] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.10
[09:52:50.082] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.5
[09:52:50.082] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2021.3.25
[09:52:50.082] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[09:52:50.083] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[09:52:50.083] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[09:52:50.084] [Il2CppAssemblyGenerator] Checking GameAssembly...
[09:52:50.183] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.
[NewEntryPoint] Starting.

[09:52:50.184] Loading Mods from 'E:\Sea of Stars\Mods'...
[09:52:50.185] ------------------------------
[09:52:50.187] Melon Assembly loaded: '.\Mods\XUnity.AutoTranslator.Plugin.MelonMod.dll'
[09:52:50.187] SHA256 Hash: '44453b0c2786d57e229e1e394f3a4d6b35011deb4e4ff6654e007859c0485347'

[09:52:50.218] ------------------------------
[09:52:50.219] XUnity Auto Translator v5.3.0
[09:52:50.219] by gravydevsupreme
[09:52:50.219] Assembly: XUnity.AutoTranslator.Plugin.MelonMod.dll
[09:52:50.220] ------------------------------
[09:52:50.220] ------------------------------
[09:52:50.220] 1 Mod loaded.

[09:52:50.312] Console Cleaner Failed: System.Exception: Unable to Find Constructor of Type Il2CppSystem.IO.StreamWriter!
   at MelonLoader.Support.Main.ConsoleCleaner() in D:\a\MelonLoader\MelonLoader\Dependencies\SupportModules\Il2Cpp\Main.cs:line 88
[09:52:50.852] Class::Init signatures have been exhausted, using a substitute!
[09:52:50.869] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[09:52:50.893] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[09:52:50.895] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[09:52:50.900] Support Module Loaded: E:\Sea of Stars\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[09:52:50.981] Registered mono type XUnity.AutoTranslator.Plugin.Core.PluginLoader+AutoTranslatorProxyBehaviour in il2cpp domain
[09:52:51.002] Screen resolution determine to be: 1920x1080
[09:52:51.003] Force loading ALL proxy assemblies.
[09:52:51.004] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Assembly-CSharp-firstpass.dll
[09:52:51.005] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll
[09:52:51.144] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppAk.Wwise.Api.WAAPI.dll
[09:52:51.147] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppAK.Wwise.Unity.API.dll
[09:52:51.158] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppAK.Wwise.Unity.API.WwiseTypes.dll
[09:52:51.159] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppAK.Wwise.Unity.MonoBehaviour.dll
[09:52:51.162] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppAK.Wwise.Unity.Timeline.dll
[09:52:51.163] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppAOTTypes.dll
[09:52:51.164] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppBzk.Async.dll
[09:52:51.165] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppConstants.dll
[09:52:51.167] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppDomainReloadHelper.Runtime.dll
[09:52:51.168] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppFacepunch.Steamworks.Win64.dll
[09:52:51.173] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppHBAO.Universal.Runtime.dll
[09:52:51.175] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppMeshCombineStudio.Runtime.dll
[09:52:51.179] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppMeshExtension.dll
[09:52:51.180] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppMono.Security.dll
[09:52:51.183] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll
[09:52:51.184] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppNavMeshComponents.dll
[09:52:51.186] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppOdinAOTSupport.dll
[09:52:51.187] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppOdinSerializer.dll
[09:52:51.194] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppPlugins.MarchingCubes.dll
[09:52:51.195] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppPlugins.ProceduralNoise.dll
[09:52:51.197] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppPlugins.Voxelizer.dll
[09:52:51.198] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppRewired_Core.dll
[09:52:51.208] An error occurred while force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppRewired_Core.dll
System.BadImageFormatException: Could not load file or assembly 'Il2CppRewired_Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, processorArchitecture=MSIL'. Tentativo di caricare un programma con un formato non corretto.
File name: 'Il2CppRewired_Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, processorArchitecture=MSIL' ---> System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at MelonLoader.Fixes.DotnetAssemblyLoadContextFix.PreAlcLoadFromPath(String ilPath) in D:\a\MelonLoader\MelonLoader\MelonLoader\Fixes\DotnetAssemblyLoadContextFix.cs:line 91
   at NativeDetour_Wrapper<System.Runtime.Loader.AssemblyLoadContext::LoadFromPath>?0(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at MelonLoader.Fixes.DotnetLoadFromManagedFolderFix.TryLoad(AssemblyLoadContext alc, String path) in D:\a\MelonLoader\MelonLoader\MelonLoader\Fixes\DotnetLoadFromManagedFolderFix.cs:line 32
   at MelonLoader.Fixes.DotnetLoadFromManagedFolderFix.OnResolve(AssemblyLoadContext alc, AssemblyName name) in D:\a\MelonLoader\MelonLoader\MelonLoader\Fixes\DotnetLoadFromManagedFolderFix.cs:line 53
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at XUnity.Common.Constants.UnityTypes.Initialize()
[09:52:51.208] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppRewired_Windows.dll
[09:52:51.212] An error occurred while force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppRewired_Windows.dll
System.BadImageFormatException: Could not load file or assembly 'Il2CppRewired_Windows, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, processorArchitecture=MSIL'. Tentativo di caricare un programma con un formato non corretto.
File name: 'Il2CppRewired_Windows, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, processorArchitecture=MSIL' ---> System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at MelonLoader.Fixes.DotnetAssemblyLoadContextFix.PreAlcLoadFromPath(String ilPath) in D:\a\MelonLoader\MelonLoader\MelonLoader\Fixes\DotnetAssemblyLoadContextFix.cs:line 91
   at NativeDetour_Wrapper<System.Runtime.Loader.AssemblyLoadContext::LoadFromPath>?0(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at MelonLoader.Fixes.DotnetLoadFromManagedFolderFix.TryLoad(AssemblyLoadContext alc, String path) in D:\a\MelonLoader\MelonLoader\MelonLoader\Fixes\DotnetLoadFromManagedFolderFix.cs:line 32
   at MelonLoader.Fixes.DotnetLoadFromManagedFolderFix.OnResolve(AssemblyLoadContext alc, AssemblyName name) in D:\a\MelonLoader\MelonLoader\MelonLoader\Fixes\DotnetLoadFromManagedFolderFix.cs:line 53
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at XUnity.Common.Constants.UnityTypes.Initialize()
[09:52:51.212] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppRewired_Windows_Functions.dll
[09:52:51.214] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.Blackboard.dll
[09:52:51.215] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.BlockGrid.dll
[09:52:51.219] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.Boids.dll
[09:52:51.220] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.Core.dll
[09:52:51.226] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.GameAssets.dll
[09:52:51.227] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.GameplayConditions.dll
[09:52:51.228] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.Geometry.dll
[09:52:51.231] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.GlobalEmission.dll
[09:52:51.232] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.Graph.dll
[09:52:51.236] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.JobSystemBoids.dll
[09:52:51.238] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.Localization.dll
[09:52:51.239] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.Ocean.dll
[09:52:51.241] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.Platform.dll
[09:52:51.242] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.Pooling.dll
[09:52:51.243] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.RenderPass.dll
[09:52:51.246] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSabotage.StateMachine.dll
[09:52:51.247] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSystem.Configuration.dll
[09:52:51.248] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSystem.Core.dll
[09:52:51.251] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSystem.dll
[09:52:51.268] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSystem.Numerics.dll
[09:52:51.270] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppSystem.Xml.dll
[09:52:51.315] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppTechArt.Runtime.dll
[09:52:51.317] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppTimeOfDay.dll
[09:52:51.319] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppVerletRope.dll
[09:52:51.320] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Il2CppWhinarn.UnityMeshSimplifier.Runtime.dll
[09:52:51.321] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.Addressables.dll
[09:52:51.325] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.Burst.dll
[09:52:51.326] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.Burst.Unsafe.dll
[09:52:51.327] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.Collections.dll
[09:52:51.330] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.InternalAPIEngineBridge.021.dll
[09:52:51.331] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.Jobs.dll
[09:52:51.332] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.Mathematics.dll
[09:52:51.334] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.Polybrush.dll
[09:52:51.335] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.ProBuilder.dll
[09:52:51.341] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.ProBuilder.KdTree.dll
[09:52:51.342] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.ProBuilder.Poly2Tri.dll
[09:52:51.344] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.ProGrids.dll
[09:52:51.345] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.RenderPipeline.Universal.ShaderLibrary.dll
[09:52:51.346] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.RenderPipelines.Core.Runtime.dll
[09:52:51.354] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.RenderPipelines.Universal.Runtime.dll
[09:52:51.369] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.ResourceManager.dll
[09:52:51.372] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.Splines.dll
[09:52:51.374] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.TextMeshPro.dll
[09:52:51.382] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.Timeline.dll
[09:52:51.386] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\Unity.VisualEffectGraph.Runtime.dll
[09:52:51.387] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.AccessibilityModule.dll
[09:52:51.388] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.AIModule.dll
[09:52:51.390] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.AndroidJNIModule.dll
[09:52:51.392] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.AnimationModule.dll
[09:52:51.398] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.ARModule.dll
[09:52:51.399] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.AssetBundleModule.dll
[09:52:51.400] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.AudioModule.dll
[09:52:51.403] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.ClothModule.dll
[09:52:51.404] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.ClusterInputModule.dll
[09:52:51.406] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.ClusterRendererModule.dll
[09:52:51.407] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll
[09:52:51.407] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.CrashReportingModule.dll
[09:52:51.408] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.DirectorModule.dll
[09:52:51.409] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.dll
[09:52:51.410] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.DSPGraphModule.dll
[09:52:51.411] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.GameCenterModule.dll
[09:52:51.413] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.GIModule.dll
[09:52:51.414] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.GridModule.dll
[09:52:51.415] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.HotReloadModule.dll
[09:52:51.416] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.ImageConversionModule.dll
[09:52:51.417] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.IMGUIModule.dll
[09:52:51.421] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.InputLegacyModule.dll
[09:52:51.423] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.InputModule.dll
[09:52:51.424] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.JSONSerializeModule.dll
[09:52:51.425] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.LocalizationModule.dll
[09:52:51.426] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.NVIDIAModule.dll
[09:52:51.427] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.ParticleSystemModule.dll
[09:52:51.430] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.PerformanceReportingModule.dll
[09:52:51.431] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.Physics2DModule.dll
[09:52:51.435] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.PhysicsModule.dll
[09:52:51.439] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.ProfilerModule.dll
[09:52:51.440] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll
[09:52:51.441] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.ScreenCaptureModule.dll
[09:52:51.442] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.SharedInternalsModule.dll
[09:52:51.444] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.SpriteMaskModule.dll
[09:52:51.445] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.SpriteShapeModule.dll
[09:52:51.446] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.StreamingModule.dll
[09:52:51.447] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.SubstanceModule.dll
[09:52:51.448] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.SubsystemsModule.dll
[09:52:51.449] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.TerrainModule.dll
[09:52:51.451] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.TerrainPhysicsModule.dll
[09:52:51.452] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.TextCoreFontEngineModule.dll
[09:52:51.454] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.TextCoreTextEngineModule.dll
[09:52:51.458] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.TextRenderingModule.dll
[09:52:51.459] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.TilemapModule.dll
[09:52:51.461] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.TLSModule.dll
[09:52:51.462] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UI.dll
[09:52:51.468] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UIElementsModule.dll
[09:52:51.490] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UIElementsNativeModule.dll
[09:52:51.492] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UIModule.dll
[09:52:51.494] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UmbraModule.dll
[09:52:51.494] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UNETModule.dll
[09:52:51.497] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UnityAnalyticsCommonModule.dll
[09:52:51.498] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UnityAnalyticsModule.dll
[09:52:51.499] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UnityConnectModule.dll
[09:52:51.500] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UnityCurlModule.dll
[09:52:51.502] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UnityTestProtocolModule.dll
[09:52:51.502] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestAssetBundleModule.dll
[09:52:51.503] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestAudioModule.dll
[09:52:51.505] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestModule.dll
[09:52:51.506] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestTextureModule.dll
[09:52:51.507] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.UnityWebRequestWWWModule.dll
[09:52:51.508] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.VehiclesModule.dll
[09:52:51.510] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.VFXModule.dll
[09:52:51.511] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.VideoModule.dll
[09:52:51.513] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.VirtualTexturingModule.dll
[09:52:51.514] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.VRModule.dll
[09:52:51.515] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.WindModule.dll
[09:52:51.516] Force loading assembly: E:\Sea of Stars\MelonLoader\Il2CppAssemblies\UnityEngine.XRModule.dll
[09:52:51.540] Could not find 'UnityEngine.TextMesh' in IL2CPP domain even though it could be found in the managed domain.
[09:52:51.542] Could not find 'UnityEngine.WWW' in IL2CPP domain even though it could be found in the managed domain.
[09:52:51.543] Could not find 'UnityEngine.GUI+ToolbarButtonSize' in IL2CPP domain even though it could be found in the managed domain.
[09:52:51.543] Could not find 'UnityEngine.ImageConversion' in IL2CPP domain even though it could be found in the managed domain.
[09:52:51.640] Hooked UnityEngine.UI.Text.set_text through Harmony hooks.
[09:52:51.652] Hooked UnityEngine.UI.Text.OnEnable through Harmony hooks.
[09:52:51.684] Disabling certificate checks for endpoints because of configuration.
[09:52:51.685] Probing whether OnLevelWasLoaded or SceneManager is supported in this version of Unity. Any warnings related to OnLevelWasLoaded coming from Unity can safely be ignored.
[09:52:51.685] SceneManager is supported in this version of Unity.
[09:52:51.688] Loaded resize command text files.
[09:52:51.699] --- Loading Global Translations ---
[09:52:51.702] Loaded translation text files (took 0 seconds)
[09:52:51.702] Created variation translations (took -0 seconds)
[09:52:51.702] Created token translations (took -0 seconds)
[09:52:51.705] Loaded XUnity.AutoTranslator into Unity [2021.3.25f1] game.
[09:52:51.717] Registered mono type XUnity.AutoTranslator.Plugin.Core.Il2CppManagedEnumerator in il2cpp domain
[09:52:51.785] Input API is not available!
System.TypeLoadException: Could not load type 'UnityEngine.Input' from assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInput()
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInputSafe()
[09:52:51.852] Skipping plugin scan because no plugin-specific translations has been registered.

**Comment by ManlyMarco** [comment]
It should be. Fixed the input issue in #531
