### ISSUE TITLE
Installed but not working

### ISSUE THREAD

**Issue by Freminace** [bbepis/XUnity.AutoTranslator#477]
In console all looks good
```
Setup completed. Press any key to exit.
```
But when i tried to press "alt+1" or "alt+0" in game nothing happen...
Thats means this game is not compatible with XUnity.AutoTranslator?
Thanks in advance!

**Comment by Freminace** [comment]
Founded errors in console

`[Error  :     Unity] Exception: Reentering the Update method is not allowed.  This can happen when calling WaitForCompletion on an operation while inside of a callback.
[Error  :XUnity.AutoTranslator] An unexpected error occurred during maintenance.
System.MissingMethodException: Method not found: 'IntPtr Il2CppInterop.Runtime.IL2CPP.il2cpp_gchandle_get_target(UInt32)'.
   at XUnity.Common.Extensions.ObjectExtensions.IsCollected(Il2CppObjectBase that)
   at XUnity.Common.Utilities.ExtensionDataHelper.Cull()
   at XUnity.Common.Utilities.MaintenanceHelper.MaintenanceLoop(Object state)
[Error  :XUnity.AutoTranslator] An unexpected error occurred during maintenance.
System.MissingMethodException: Method not found: 'IntPtr Il2CppInterop.Runtime.IL2CPP.il2cpp_gchandle_get_target(UInt32)'.
   at XUnity.Common.Extensions.ObjectExtensions.IsCollected(Il2CppObjectBase that)
   at XUnity.Common.Utilities.ExtensionDataHelper.Cull()
   at XUnity.Common.Utilities.MaintenanceHelper.MaintenanceLoop(Object state)
[Error  :XUnity.AutoTranslator] An unexpected error occurred during maintenance.
System.MissingMethodException: Method not found: 'IntPtr Il2CppInterop.Runtime.IL2CPP.il2cpp_gchandle_get_target(UInt32)'.
   at XUnity.Common.Extensions.ObjectExtensions.IsCollected(Il2CppObjectBase that)
   at XUnity.Common.Utilities.ExtensionDataHelper.Cull()
   at XUnity.Common.Utilities.MaintenanceHelper.MaintenanceLoop(Object state)`
