### ISSUE TITLE
How to use XUnity.ResourceRedirector alone without AutoTranslator?

### ISSUE THREAD

**Issue by jyxjyx1234** [bbepis/XUnity.AutoTranslator#646]
The game シロクロ ～色情症の幼馴染を世話することになった、彼女にナイショで～ uses il2CPP and fails to launch when AutoTranslator is used. I successfully extracted the game's script files in TXT format and translated them. Unfortunately, I was unable to repackage the files as I couldn’t locate the file index for repackaging. Is it possible to use XUnity.ResourceRedirector to load the translated script files instead? Or how to fix the AutoTranslator?

The errors infomation when use AutoTranslator：
[Message: Preloader] BepInEx 6.0.0-be.729 - SHIROKURO (2024/11/25 16:17:22)
[Message: Preloader] Built from commit 35f6b1b541819897e2d80fc08b98e0f8e4880f33
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 6000.0.23f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [XUnity Auto Translator 5.4.3]
[Info   :Il2CppInterop] Registered mono type XUnity.AutoTranslator.Plugin.Core.PluginLoader+AutoTranslatorProxyBehaviour in il2cpp domain
[Info   :   BepInEx] Loading [XUnity Resource Redirector 2.1.0]
[Message:   BepInEx] Chainloader startup complete
[Info   :XUnity.AutoTranslator] Force loading ALL proxy assemblies.
[Warning:XUnity.AutoTranslator] An error occurred while resolving type: UnityEngine.TextMesh
System.ArgumentException: TextMesh does not have a corresponding IL2CPP class pointer
   at Il2CppInterop.Runtime.Il2CppType.TypeFromPointerInternal(IntPtr classPointer, String typeName, Boolean throwOnFailure) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppType.cs:line 19
   at XUnity.Common.Constants.UnityTypes.FindType(String name)
[Warning:XUnity.AutoTranslator] An error occurred while resolving type: UnityEngine.WWW
System.ArgumentException: WWW does not have a corresponding IL2CPP class pointer
   at Il2CppInterop.Runtime.Il2CppType.TypeFromPointerInternal(IntPtr classPointer, String typeName, Boolean throwOnFailure) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppType.cs:line 19
   at XUnity.Common.Constants.UnityTypes.FindType(String name)
[Error  :Il2CppInterop] Nested type ToolbarButtonSize on GUI not found!
[Warning:XUnity.AutoTranslator] An error occurred while resolving type: UnityEngine.GUI+ToolbarButtonSize
System.ArgumentException: ToolbarButtonSize does not have a corresponding IL2CPP class pointer
   at Il2CppInterop.Runtime.Il2CppType.TypeFromPointerInternal(IntPtr classPointer, String typeName, Boolean throwOnFailure) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppType.cs:line 19
   at XUnity.Common.Constants.UnityTypes.FindType(String name)
[Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [] game.
[Info   :Il2CppInterop] Registered mono type XUnity.AutoTranslator.Plugin.Core.Il2CppManagedEnumerator in il2cpp domain
[Info   :XUnity.AutoTranslator] Skipping plugin scan because no plugin-specific translations has been registered.
[Message:     Unity] 鍒濇湡銈ゃ儥銉炽儓闁嬪-> _autoboot.lua
[Message:     Unity] key[00_銉栥儵銉炽儔銉偞.lua]=1
(then game crashed)

The txt file I got：
![image](https://github.com/user-attachments/assets/3db55453-8c83-45f1-9e8b-73d381c44b71)

**Comment by jyxjyx1234** [comment]
I have already implemented the replacement of the game script myself using a simple inline hook. Sorry for the trouble!
